/* Generated By:JavaCC: Do not edit this line. compConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INSTRUCOES = 5;
  /** RegularExpression Id. */
  int FUNCOES = 6;
  /** RegularExpression Id. */
  int COMANDOS = 7;
  /** RegularExpression Id. */
  int TIPOS = 8;
  /** RegularExpression Id. */
  int BOOLEANAS = 9;
  /** RegularExpression Id. */
  int NUMEROS = 10;
  /** RegularExpression Id. */
  int IDENTIFICADOR = 11;
  /** RegularExpression Id. */
  int IDENTIFICADORES = 12;
  /** RegularExpression Id. */
  int OPERADORES = 13;
  /** RegularExpression Id. */
  int MAIN = 14;
  /** RegularExpression Id. */
  int PROGRAMA = 15;
  /** RegularExpression Id. */
  int LPAREN = 16;
  /** RegularExpression Id. */
  int RPAREN = 17;
  /** RegularExpression Id. */
  int LCHAVE = 18;
  /** RegularExpression Id. */
  int RCHAVE = 19;
  /** RegularExpression Id. */
  int SIMBOLOS = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<INSTRUCOES>",
    "<FUNCOES>",
    "<COMANDOS>",
    "<TIPOS>",
    "<BOOLEANAS>",
    "<NUMEROS>",
    "<IDENTIFICADOR>",
    "<IDENTIFICADORES>",
    "<OPERADORES>",
    "\"public static void Main() \"",
    "\"Program \"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "<SIMBOLOS>",
  };

}
