/* Generated By:JavaCC: Do not edit this line. compConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface compConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int INSTRUCOES = 5;
  /** RegularExpression Id. */
  int INSTRUCAO_THEN = 6;
  /** RegularExpression Id. */
  int INSTRUCAO_DO = 7;
  /** RegularExpression Id. */
  int FUNCOES = 8;
  /** RegularExpression Id. */
  int COMANDOS = 9;
  /** RegularExpression Id. */
  int TIPOS = 10;
  /** RegularExpression Id. */
  int BOOLEANAS = 11;
  /** RegularExpression Id. */
  int NUMEROS = 12;
  /** RegularExpression Id. */
  int SIMBOLOS_ESPECIAIS = 13;
  /** RegularExpression Id. */
  int IDENTIFICADORES = 14;
  /** RegularExpression Id. */
  int OPERADORES = 15;
  /** RegularExpression Id. */
  int MAIN = 16;
  /** RegularExpression Id. */
  int PROGRAMA = 17;
  /** RegularExpression Id. */
  int LPAREN = 18;
  /** RegularExpression Id. */
  int RPAREN = 19;
  /** RegularExpression Id. */
  int LCHAVE = 20;
  /** RegularExpression Id. */
  int RCHAVE = 21;
  /** RegularExpression Id. */
  int LCOLCHETE = 22;
  /** RegularExpression Id. */
  int RCOLCHETE = 23;
  /** RegularExpression Id. */
  int SIMBOLOS = 24;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<INSTRUCOES>",
    "\"then\"",
    "\"do\"",
    "<FUNCOES>",
    "<COMANDOS>",
    "<TIPOS>",
    "<BOOLEANAS>",
    "<NUMEROS>",
    "<SIMBOLOS_ESPECIAIS>",
    "<IDENTIFICADORES>",
    "<OPERADORES>",
    "\"public static void Main() \"",
    "\"Program \"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "<SIMBOLOS>",
  };

}
